image: gradle:jdk11

before_script:
  - echo 'before_script start...'

stages:
  - pull_and_update_prod

pull_and_update_prod:
  stage: pull_and_update_prod
  script:
    - echo "PROD" > key.pem
  only:
    - main
